language: android
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk: oraclejdk8
android:
  components:
  - build-tools-22.0.1
  - android-22
  - android-7
  - extra
script: './gradlew build check'
before_install:
- openssl aes-256-cbc -K $encrypted_69044bd0f1e4_key -iv $encrypted_69044bd0f1e4_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
after_success: './gradlew publishApkRelease'
deploy:
  provider: releases
  api_key:
    secure: X9fnLUh/qKVwtDOFicmHBZN3r0sEnM3kp4st/vjRCuDgTV30pG/0y3kjnbSuRm/Qgw8sgvzD5RlGQ7aHiU6naJnlrAbBeHVs3EECMvRc2zZjeUGCg4Iwtd0rPnvl2X28jOFTOeOM24FP6cqhVK/keilLcTCjB4llTYjbV4FkIqo=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: larsgrefer/bpm-meter-android
    tags: true
