language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
script: './gradlew build check'
after_failure: 'cat app/build/outputs/lint-results.xml'
before_install:
- openssl aes-256-cbc -K $encrypted_69044bd0f1e4_key -iv $encrypted_69044bd0f1e4_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
deploy:
  provider: releases
  api_key:
    secure: X9fnLUh/qKVwtDOFicmHBZN3r0sEnM3kp4st/vjRCuDgTV30pG/0y3kjnbSuRm/Qgw8sgvzD5RlGQ7aHiU6naJnlrAbBeHVs3EECMvRc2zZjeUGCg4Iwtd0rPnvl2X28jOFTOeOM24FP6cqhVK/keilLcTCjB4llTYjbV4FkIqo=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: larsgrefer/bpm-meter-android
    tags: true
